two_wheels_robot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    camera1_position_controller:
        type: effort_controllers/JointPositionController
        joint: camera1_joint
        pid: {p: 1.0, i: 0.1, d: 0.0}